{
  imports = [
    ../modules/programs/steam.nix
    ../modules/programs/desktop.nix
    ../modules/programs/thunar.nix
    ../modules/programs/neovim.nix
    ../modules/programs/virt-manager.nix
    ../modules/services/flatpak.nix
    ../modules/services/polkit.nix
    ../modules/services/waydroid-nvidia.nix
    ../modules/services/openssh.nix
    ../modules/services/pipewire.nix
    ../modules/services/guix.nix
    ../modules/services/linyaps.nix
    ../modules/security/sudo-rs.nix
    ../modules/security/wrappers.nix
    ../modules/virtualisation/libvirtd.nix
    ../modules/virtualisation/podman.nix
    ../modules/virtualisation/vmware-workstation.nix
  ];
}
