window_padding_width 5
cursor_shape beam
hide_window_decorations no
background_opacity 0.75
# font_family JetBrains Maple Mono 
font_size 13.5
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1
# cursor_text_color background
shell_integration no-cursor
window_border_width 0
# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Noctalia
include themes/noctalia.conf
# END_KITTY_THEME
